# SPDX-FileCopyrightText: © 2025 Phala Network <dstack@phala.network>
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "no_std_check"
version = "0.1.0"
edition = "2021"

[dependencies]
dstack-sdk-types = { workspace = true, features = ["borsh"] }
