name: SDK tests

on:
  push:
    branches: [ master, next, dev-* ]
  pull_request:
    branches: [ master, next, dev-* ]

env:
  CARGO_TERM_COLOR: always

jobs:
  sdk-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@1.86
      with:
        components: clippy, rustfmt

    - name: SDK tests
      run: cd sdk && ./run-tests.sh
