# SPDX-FileCopyrightText: © 2025 Daniel Sharifi <daniel.sharifi@nearone.org>
# SPDX-FileCopyrightText: © 2025 Phala Network <dstack@phala.network>
#
# SPDX-License-Identifier: Apache-2.0

name: SDK tests
permissions:
  contents: read

on:
  push:
    branches: [master, next, dev-*]
  pull_request:
    branches: [master, next, dev-*]

env:
  CARGO_TERM_COLOR: always

jobs:
  sdk-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.86
        with:
          components: clippy, rustfmt
          # This additional target is needed for wasm32 compatibility check.
          targets: wasm32-unknown-unknown, thumbv6m-none-eabi

      - name: SDK tests
        run: cd sdk && ./run-tests.sh

      - name: Verify WASM compilation
        # Ensures SDK types can be used in smart contracts
        run: cargo check --target=wasm32-unknown-unknown -p dstack-sdk-types

      - name: Verify no_std compatibility
        run: |
          cargo test -p dstack-sdk-types --test no_std_test --no-default-features
          cargo check -p no_std_check --target thumbv6m-none-eabi
